[project]
name = "Qupbit"
version = "0.0.1"
dependencies = [
        'python-dateutil',
        'pytz',
        'requests',
        'websockets',
        'httpx'
    ]
[tool.setuptools]
packages = ["Qupbit"]