[project]
name = "Qprocon"
version = "0.0.2"
dependencies = ["ntplib","pytz"]

[tool.setuptools]
packages = ["Qprocon"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"